server:
  forward-headers-strategy: framework
  port: 8082

####### resource server configuration properties
spring:
  webflux:
    base-path: /resource-server
  jpa:
    defer-datasource-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_SERVER:http://127.0.0.1:8083}
springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1
  swagger-ui:
    oauth:
      clientId: newClient
      clientSecret: newClientSecret
  oAuthFlow:
    authorizationUrl: ${OAUTH2_SERVER:http://127.0.0.1:8083}/oauth2/authorize
    tokenUrl: ${OAUTH2_SERVER:http://127.0.0.1:8083}/oauth2/token
